const validCase = {
	path: "/home/user/notes/Project/Plan.md",
	taskOngoing: "-[] Task",
	taskOngoing2: "-[][] Task",
	taskOngoing3: "-[][][] Task",
	taskOngoing4: "-[][][][] Task",
	taskOngoing5: "-[][][][][] Task",
	taskOngoing6: "-[][][][][][] Task",
	taskOngoing7: "-[][][][][][][] Task",
	taskOngoingWithPreview:  "-[] Prefix: Task",
	taskOngoingWithPreview2: "-[][] Prefix: Task",
	taskOngoingWithPreview3: "-[][][] Prefix: Task",
	taskOngoingWithPreview4: "-[][][][] Prefix: Task",
	taskOngoingWithPreview5: "-[][][][][] Prefix: Task",
	taskOngoingWithPreview6: "-[][][][][][] Prefix: Task",
	taskOngoingWithPreview7: "-[][][][][][][] Prefix: Task",
	taskCompleted:  "-[x] Task (Completed)",
	taskCompleted2: "-[x][] Task (Completed)",
	taskCompleted3: "-[x][][][] Task (Completed)",
	taskCompleted4: "-[x][][][][] Task (Completed)",
	taskCompleted5: "-[x][][][][][] Task (Completed)",
	taskCompleted6: "-[x][][][][][][] Task (Completed)",
	taskCompleted7: "-[x][][][][][][][] Task (Completed)",
	taskCompletedWithPreview:  "-[x][] Prefix: Task (Completed)",
	taskCompletedWithPreview2: "-[x][][] Prefix: Task (Completed)",
	taskCompletedWithPreview3: "-[x][][][] Prefix: Task (Completed)",
	taskCompletedWithPreview4: "-[x][][][][] Prefix: Task (Completed)",
	taskCompletedWithPreview5: "-[x][][][][][] Prefix: Task (Completed)",
	taskCompletedWithPreview6: "-[x][][][][][][] Prefix: Task (Completed)",
	taskCompletedWithPreview7: "-[x][][][][][][][] Prefix: Task (Completed)",
	groupFlat: "root",
	groupFile: "Plan",
	groupFolder: "Project",
	groupOverride: "Prefix",
	groupFileSub: "Plan-Prefix",
	groupFolderSub: "Project-Prefix",
	taskName: "Task"
}

module.exports = {
	validCase
};
